Repository ShafinRME/the-delta-times-server, pull requests merged in 2022-09, with the labels that each got.

#66 entertainment and environment sub category and photos routes is done.
  controllers/moderator.controller.js
  controllers/photos.controller.js
  routes/moderator.route.js
  routes/photos.route.js
Labels: enhancement

#67 Main
  controllers/moderator.controller.js
  controllers/photos.controller.js
  controllers/users.controller.js
  routes/moderator.route.js
  routes/photos.route.js
  routes/users.route.js
Labels: enhancement

#68 Dt fix bug mod api 65
  controllers/moderator.controller.js
  controllers/users.controller.js
  routes/users.route.js
Labels: bug, duplicate

#70 #65 fix some error
  controllers/users.controller.js
  routes/users.route.js
Labels: bug, enhancement

#71 new subcategory and subcategory slug news is done.
  app.js
  controllers/moderator.controller.js
  controllers/slug.controller.js
  routes/moderator.route.js
  routes/slug.route.js
Labels: enhancement

#72 features to main transfer
  app.js
  controllers/moderator.controller.js
  controllers/slug.controller.js
  routes/moderator.route.js
  routes/slug.route.js
Labels: enhancement

#69 Dt fix bug mod api 65
  controllers/moderator.controller.js
  controllers/users.controller.js
  routes/users.route.js
Labels: bug, enhancement

#74 fix error
  models/moderator.news.model.js
  models/users.model.js
Labels: bug, enhancement
